### PR TITLE
13 package json missing babel config

### LINKED ISSUE #13: package.json missing babel config
Tried to build and babel acts like it's never seen React before. Added the config that was removed in this commit (https://github.com/ClearBlade/cb-dev-kit/commit/9123912919f284dbb57a2e7a4c56a02e05abdc9d) and all is good

### PR DESCRIPTION
**Pull request by hsmeans**
Closes #13 

- Re-added babel config
- Updated React component template
- Added snapshot tests for basic templates

### CODE REVIEW

**Comment by aalcott14** [comment]
I agree it would be nice to check the whole generated package.json. I think this could be accomplished if you alter the cmds/init.js module to export two items... one that exports the function that is used when the command is executed and a second that simply handles building the package.json string that would then get used in the first.
Also existing unit tests you added look great!

**Comment by hsmeans** [comment]
Added the test by changing init.js by doing what Adam suggested. Also updated the index.js to compensated for the change.

**Comment by sh3nan1gans** [comment]
lgtm. @aalcott14 ?

**Comment by aalcott14** [comment]
looks good

**Pull request merged**
